<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KontribusiDropDownIcon</name>
   <tag></tag>
   <elementGuidId>7e7b1bab-7943-44fc-a191-aaca2a7159b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[3]/div/div[1]/div/ion-label/button/button/span/ion-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-1046-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[3]/div/div[1]/div/ion-label/button/button/span/ion-icon</value>
   </webElementProperties>
</WebElementEntity>
