<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PolicyNumberObject</name>
   <tag></tag>
   <elementGuidId>2f39adcc-1144-4bcf-b6c2-9ba82235a6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[1]/div/div[1]/div/ion-label/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-input/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[1]/div/div[1]/div/ion-label/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-input/input</value>
   </webElementProperties>
</WebElementEntity>
