<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newbusiness</name>
   <tag></tag>
   <elementGuidId>510af7e0-d939-4e9f-8089-2897c5cb0e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-app/ng-component/ion-menu[1]/div/ion-content/div[2]/ion-list/div/div/div[1]/ion-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ng-component/ion-menu[1]/div/ion-content/div[2]/ion-list/div/div/div[1]/ion-icon</value>
   </webElementProperties>
</WebElementEntity>
