<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ViewByObject</name>
   <tag></tag>
   <elementGuidId>135c7041-39dd-499d-a670-eae6590b1309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-list/ion-content/div[2]/ion-grid[1]/ion-row[2]/ion-col[1]/ion-item/div[1]/div/ion-select/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-list/ion-content/div[2]/ion-grid[1]/ion-row[2]/ion-col[1]/ion-item/div[1]/div/ion-select/button/span</value>
   </webElementProperties>
</WebElementEntity>
