<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bulan TU</name>
   <tag></tag>
   <elementGuidId>5135d3f0-e02d-434b-9b7d-810a468266e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-opt-selected:nth-child(3)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>button.picker-opt-selected:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ion-picker-cmp/div/div[2]/div[3]/div/button[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button.picker-opt-selected:nth-child(3)</value>
   </webElementProperties>
</WebElementEntity>
