<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tahun TU</name>
   <tag></tag>
   <elementGuidId>558d7b13-d90b-4185-afe8-1ff7395f7021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-opt-selected:nth-child(23)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>button.picker-opt-selected:nth-child(23)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ion-picker-cmp/div/div[2]/div[4]/div/button[4]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button.picker-opt-selected:nth-child(23)</value>
   </webElementProperties>
</WebElementEntity>
