<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tgl_TU</name>
   <tag></tag>
   <elementGuidId>c23badb2-c224-41b9-804f-a5f06dd7b1cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-opt-selected:nth-child(15)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>button.picker-opt-selected:nth-child(15)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ion-picker-cmp/div/div[2]/div[2]/div/button[19]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button.picker-opt-selected:nth-child(15)</value>
   </webElementProperties>
</WebElementEntity>
