<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>821ea18f-2c65-4578-b7ec-dee000ad36b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='PRU'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ion-app[@class=&quot;app-root app-root-ios ios platform-core enable-hover&quot;]/ng-component[@class=&quot;app-root&quot;]/ion-nav[@class=&quot;main-content menu-content menu-content-push menu-content-reveal&quot;]/page-login[@class=&quot;ion-page show-page&quot;]/ion-content[@class=&quot;login-content content content-ios&quot;]/div[@class=&quot;scroll-content&quot;]/div[@class=&quot;login-box&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/ion-row[@class=&quot;row&quot;]/ion-col[@class=&quot;signup-col col&quot;]/button[@class=&quot;submit-btn button button-ios button-default button-default-ios button-full button-full-ios activated&quot;]/span[@class=&quot;button-inner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRU'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button/span</value>
   </webElementXpaths>
</WebElementEntity>
