<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yes_PemegangPolis</name>
   <tag></tag>
   <elementGuidId>94e68202-09a0-405d-b1f0-9b48477760f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[4]/div/div[1]/div/ion-label/div/ion-row/ion-col[6]/ion-list/ion-item[1]/div[1]/ion-radio/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ion-app/ng-component/ion-nav/page-phs-workbasket-quotation/ion-content/div[2]/ion-grid/ion-row[2]/ion-col[2]/expandable[4]/div/div[1]/div/ion-label/div/ion-row/ion-col[6]/ion-list/ion-item[1]/div[1]/ion-radio/button/span</value>
   </webElementProperties>
</WebElementEntity>
